kinoprogramm_url: "https://www.kinoprogramm.com/kino/konstanz-universitaetsstadt/cinestar-konstanz-60996"
timezone: "Europe/Berlin"
request_timeout: 15
request_retries: 2
ov_markers:
  - "OV"
  - "OmU"
  - "Originalfassung"
  - "Originalversion"
  - "OmeU"
