kinoprogramm_url: "https://kinoprogramm.com/kino/cinestar-konstanz"
timezone: "Europe/Berlin"
request_timeout: 15
request_retries: 2
ov_markers:
  - "OV"
  - "OmU"
  - "Originalfassung"
  - "Originalversion"
  - "OmeU"
